---
- name: 'BMI计算器'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_01.png'
  url: 'http://h5.e-mxing.com/bmi'
- name: '食物热量查询'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_02.png'
  url: 'http://h5.e-mxing.com/foodcal'
- name: '运动热量查询'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_03.png'
  url: 'http://h5.e-mxing.com/fitcal'
- name: '健身计划'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_04.png'
  url: 'http://h5.e-mxing.com/fitplan'