---
- name: 'BMI计算器'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_01.png'
  title: '美型BMI计算器，一键测出您的身体质量指数.'
  url: 'http://h5.e-mxing.com/bmi'
- name: '食物热量查询'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_02.png'
  title: '美型食物热量查询，让您健身有理有据.'
  url: 'http://h5.e-mxing.com/foodcal'
- name: '运动热量查询'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_03.png'
  title: '美型运动热量查询，让您健身有理有据.'
  url: 'http://h5.e-mxing.com/fitcal'
- name: '健身计划'
  icon: 'http://7xnvtv.com2.z0.glb.qiniucdn.com/icon_04.png'
  title: '美型健身计划，一键定制专属，在家也能专业健身.'
  url: 'http://h5.e-mxing.com/fitplan'